flags:
- long: source-type-upstream
  type: boolean
  description: "Clone ansible from upstream master"
  non-empty-group: source
- long: source-type-pr
  type: integer
  description: "Clone ansible from PR merged with upstream master"
  non-empty-group: source
- long: source-type-rpm
  type: boolean
  description: "Install ansible from distribution rpm"
  non-empty-group: source
- long: resource-from-string
  type: string
  description: "Cluster resources specified by string"
  non-empty-group: inventory
- long: resource-from-file
  type: file
  description: "Cluster resource specified by file"
  non-empty-group: inventory
- long: local-inventory
  type: boolean
  description: "Inventory built from localhost"
  non-empty-group: inventory
- long: private-key
  type: file
  description: "Cluster private key"
- long: extra-vars
  type: string
  description: "Extra ansible playbook arguments"
- long: deploy
  type: string
  default: "cluster"
  description: "Deployment script to run"
  one-of: ["cluster", "etcd", "docker", "master", "node"]
- long: restart
  type: string
  default: "cluster"
  description: "Restart script to run"
  one-of: ["cluster", "etcd", "docker", "master", "node"]
- long: update
  type: string
  default: "cluster"
  description: "Update script to run"
  one-of: ["cluster", "etcd", "docker", "master", "node"]
