flags:
- long: os
  short: o
  type: string
  description: "Target OS"
  non-empty: True
  # TODO(jchaloup): extend with Fedora23, Fedora24, RHEL7.2, ...
  one-of: ["Fedora", "RHEL"]
- long: artefact-dest
  short: t
  type: directory
  description: "Target directory for artefacts"
  default-action: "set-cwd"
- long: master-url
  short: m
  type: string
  description: "Jenkin master URL"
  non-empty: True
- long: flavor
  short: f
  type: string
  description: "VM flavor"
  one-of: ["m1.small", "m3.medium", "m1.medium"]
- long: size
  short: s
  type: integer
  description: "Cluster size"
  min: 1
  max: 3
- long: with-storage-repos
  type: boolean
  description: "Include storage repos, for e2e Volume tests"
