---
name: Kubernetes related commands
description: Run CI over kubernetes builds or kubernetes deployment solutions
commands:
- name: deploy
  flags: ["deploy/deploy.yml"]
  description: "Deploy kubernetes via ansible"
image: gofed/kubernetes:v0.0.1
task: kubernetes
binary: /home/kubernetes/kubernetes.py
